FROM apache/airflow:2.9.3

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends default-jre-headless \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY docker/requirements.airflow.txt /tmp/requirements.airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements.airflow.txt
